
class Pokemon {
    constructor(name, dex, type){
        this.name = name;
        this.dex = dex;
        this.type = type;

    }

    printName() {
        console.log(this.name);
    }
    printInfo(difficulty){
        if (difficulty == 1){
            console.log(this.dex, " ", this.type);
        }
        else if (difficulty == 2){
            console.log(this.dex);
        }
    }
}


let allPokemon = [];
let increment = 1;

allPokemon.push(new Pokemon("Bulbasaur", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Ivysaur", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Venusaur", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Charmander", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Charmeleon", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Charizard", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Squirtle", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Wartortle", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Blastoise", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Caterpie", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Metapod", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Butterfree", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Weedle", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Kakuna", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Beedrill", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Pidgey", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Pidgeotto", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Pidgeot", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Rattata", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Raticate", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Spearow", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Fearow", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Ekans", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Arbok", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Pikachu", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Raichu", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Sandshrew", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Sandslash", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Nidoran", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Nidorina", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Nidoqueen", increment, "poison/ground"));
increment += 1;
allPokemon.push(new Pokemon("Nidoran", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Nidorino", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Nidoking", increment, "poison/ground"));
increment += 1;
allPokemon.push(new Pokemon("Clefairy", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Clefable", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Vulpix", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Ninetales", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Jigglypuff", increment, "normal/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Wigglytuff", increment, "normal/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Zubat", increment, "poison/flying"));
increment += 1;
allPokemon.push(new Pokemon("Golbat", increment, "poison/flying"));
increment += 1;
allPokemon.push(new Pokemon("Oddish", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Gloom", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Vileplume", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Paras", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Parasect", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Venonat", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Venomoth", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Diglett", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Dugtrio", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Meowth", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Persian", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Psyduck", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Golduck", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Mankey", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Primeape", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Growlithe", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Arcanine", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Poliwag", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Poliwhirl", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Poliwrath", increment, "water/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Abra", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Kadabra", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Alakazam", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Machop", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Machoke", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Machamp", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Bellsprout", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Weepinbell", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Victreebel", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Tentacool", increment, "water/poison"));
increment += 1;
allPokemon.push(new Pokemon("Tentacruel", increment, "water/poison"));
increment += 1;
allPokemon.push(new Pokemon("Geodude", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Graveler", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Golem", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Ponyta", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Rapidash", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Slowpoke", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Slowbro", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Magnemite", increment, "electric/steel"));
increment += 1;
allPokemon.push(new Pokemon("Magneton", increment, "electric/steel"));
increment += 1;
allPokemon.push(new Pokemon("Farfetchd", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Doduo", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Dodrio", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Seel", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Dewgong", increment, "water/ice"));
increment += 1;
allPokemon.push(new Pokemon("Grimer", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Muk", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Shellder", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Cloyster", increment, "water/ice"));
increment += 1;
allPokemon.push(new Pokemon("Gastly", increment, "ghost/poison"));
increment += 1;
allPokemon.push(new Pokemon("Haunter", increment, "ghost/poison"));
increment += 1;
allPokemon.push(new Pokemon("Gengar", increment, "ghost/poison"));
increment += 1;
allPokemon.push(new Pokemon("Onix", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Drowzee", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Hypno", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Krabby", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Kingler", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Voltorb", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Electrode", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Exeggcute", increment, "grass/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Exeggutor", increment, "grass/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Cubone", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Marowak", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Hitmonlee", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Hitmonchan", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Lickitung", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Koffing", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Weezing", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Rhyhorn", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Rhydon", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Chansey", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Tangela", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Kangaskhan", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Horsea", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Seadra", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Goldeen", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Seaking", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Staryu", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Starmie", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Mr. Mime", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Scyther", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Jynx", increment, "ice/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Electabuzz", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Magmar", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Pinsir", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Tauros", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Magikarp", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Gyarados", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Lapras", increment, "water/ice"));
increment += 1;
allPokemon.push(new Pokemon("Ditto", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Eevee", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Vaporeon", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Jolteon", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Flareon", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Porygon", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Omanyte", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Omastar", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Kabuto", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Kabutops", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Aerodactyl", increment, "rock/flying"));
increment += 1;
allPokemon.push(new Pokemon("Snorlax", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Articuno", increment, "ice/flying"));
increment += 1;
allPokemon.push(new Pokemon("Zapdos", increment, "electric/flying"));
increment += 1;
allPokemon.push(new Pokemon("Moltres", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Dratini", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Dragonair", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Dragonite", increment, "dragon/flying"));
increment += 1;
allPokemon.push(new Pokemon("Mewtwo", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Mew", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Chikorita", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Bayleef", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Meganium", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Cyndaquil", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Quilava", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Typhlosion", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Totodile", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Croconaw", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Feraligatr", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Sentret", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Furret", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Hoothoot", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Noctowl", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Ledyba", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Ledian", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Spinarak", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Ariados", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Crobat", increment, "poison/flying"));
increment += 1;
allPokemon.push(new Pokemon("Chinchou", increment, "water/electric"));
increment += 1;
allPokemon.push(new Pokemon("Lanturn", increment, "water/electric"));
increment += 1;
allPokemon.push(new Pokemon("Pichu", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Cleffa", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Igglybuff", increment, "normal/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Togepi", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Togetic", increment, "fairy/flying"));
increment += 1;
allPokemon.push(new Pokemon("Natu", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Xatu", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Mareep", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Flaaffy", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Ampharos", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Bellossom", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Marill", increment, "water/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Azumarill", increment, "water/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Sudowoodo", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Politoed", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Hoppip", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Skiploom", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Jumpluff", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Aipom", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Sunkern", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Sunflora", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Yanma", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Wooper", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Quagsire", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Espeon", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Umbreon", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Murkrow", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Slowking", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Misdreavus", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Unown", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Wobbuffet", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Girafarig", increment, "normal/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Pineco", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Forretress", increment, "bug/steel"));
increment += 1;
allPokemon.push(new Pokemon("Dunsparce", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Gligar", increment, "ground/flying"));
increment += 1;
allPokemon.push(new Pokemon("Steelix", increment, "steel/ground"));
increment += 1;
allPokemon.push(new Pokemon("Snubbull", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Granbull", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Qwilfish", increment, "water/poison"));
increment += 1;
allPokemon.push(new Pokemon("Scizor", increment, "bug/steel"));
increment += 1;
allPokemon.push(new Pokemon("Shuckle", increment, "bug/rock"));
increment += 1;
allPokemon.push(new Pokemon("Heracross", increment, "bug/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sneasel", increment, "dark/ice"));
increment += 1;
allPokemon.push(new Pokemon("Teddiursa", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Ursaring", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Slugma", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Magcargo", increment, "fire/rock"));
increment += 1;
allPokemon.push(new Pokemon("Swinub", increment, "ice/ground"));
increment += 1;
allPokemon.push(new Pokemon("Piloswine", increment, "ice/ground"));
increment += 1;
allPokemon.push(new Pokemon("Corsola", increment, "water/rock"));
increment += 1;
allPokemon.push(new Pokemon("Remoraid", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Octillery", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Delibird", increment, "ice/flying"));
increment += 1;
allPokemon.push(new Pokemon("Mantine", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Skarmory", increment, "steel/flying"));
increment += 1;
allPokemon.push(new Pokemon("Houndour", increment, "dark/fire"));
increment += 1;
allPokemon.push(new Pokemon("Houndoom", increment, "dark/fire"));
increment += 1;
allPokemon.push(new Pokemon("Kingdra", increment, "water/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Phanpy", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Donphan", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Porygon2", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Stantler", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Smeargle", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Tyrogue", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Hitmontop", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Smoochum", increment, "ice/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Elekid", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Magby", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Miltank", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Blissey", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Raikou", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Entei", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Suicune", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Larvitar", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Pupitar", increment, "rock/ground"));
increment += 1;
allPokemon.push(new Pokemon("Tyranitar", increment, "rock/dark"));
increment += 1;
allPokemon.push(new Pokemon("Lugia", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Ho-Oh", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Celebi", increment, "psychic/grass"));
increment += 1;
allPokemon.push(new Pokemon("Treecko", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Grovyle", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Sceptile", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Torchic", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Combusken", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Blaziken", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Mudkip", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Marshtomp", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Swampert", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Poochyena", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Mightyena", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Zigzagoon", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Linoone", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Wurmple", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Silcoon", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Beautifly", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Cascoon", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Dustox", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Lotad", increment, "water/grass"));
increment += 1;
allPokemon.push(new Pokemon("Lombre", increment, "water/grass"));
increment += 1;
allPokemon.push(new Pokemon("Ludicolo", increment, "water/grass"));
increment += 1;
allPokemon.push(new Pokemon("Seedot", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Nuzleaf", increment, "grass/dark"));
increment += 1;
allPokemon.push(new Pokemon("Shiftry", increment, "grass/dark"));
increment += 1;
allPokemon.push(new Pokemon("Taillow", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Swellow", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Wingull", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Pelipper", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Ralts", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Kirlia", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Gardevoir", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Surskit", increment, "bug/water"));
increment += 1;
allPokemon.push(new Pokemon("Masquerain", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Shroomish", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Breloom", increment, "grass/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Slakoth", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Vigoroth", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Slaking", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Nincada", increment, "bug/ground"));
increment += 1;
allPokemon.push(new Pokemon("Ninjask", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Shedinja", increment, "bug/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Whismur", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Loudred", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Exploud", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Makuhita", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Hariyama", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Azurill", increment, "normal/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Nosepass", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Skitty", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Delcatty", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Sableye", increment, "dark/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Mawile", increment, "steel/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Aron", increment, "steel/rock"));
increment += 1;
allPokemon.push(new Pokemon("Lairon", increment, "steel/rock"));
increment += 1;
allPokemon.push(new Pokemon("Aggron", increment, "steel/rock"));
increment += 1;
allPokemon.push(new Pokemon("Meditite", increment, "fighting/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Medicham", increment, "fighting/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Electrike", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Manectric", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Plusle", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Minun", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Volbeat", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Illumise", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Roselia", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Gulpin", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Swalot", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Carvanha", increment, "water/dark"));
increment += 1;
allPokemon.push(new Pokemon("Sharpedo", increment, "water/dark"));
increment += 1;
allPokemon.push(new Pokemon("Wailmer", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Wailord", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Numel", increment, "fire/ground"));
increment += 1;
allPokemon.push(new Pokemon("Camerupt", increment, "fire/ground"));
increment += 1;
allPokemon.push(new Pokemon("Torkoal", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Spoink", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Grumpig", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Spinda", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Trapinch", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Vibrava", increment, "ground/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Flygon", increment, "ground/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Cacnea", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Cacturne", increment, "grass/dark"));
increment += 1;
allPokemon.push(new Pokemon("Swablu", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Altaria", increment, "dragon/flying"));
increment += 1;
allPokemon.push(new Pokemon("Zangoose", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Seviper", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Lunatone", increment, "rock/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Solrock", increment, "rock/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Barboach", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Whiscash", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Corphish", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Crawdaunt", increment, "water/dark"));
increment += 1;
allPokemon.push(new Pokemon("Baltoy", increment, "ground/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Claydol", increment, "ground/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Lileep", increment, "rock/grass"));
increment += 1;
allPokemon.push(new Pokemon("Cradily", increment, "rock/grass"));
increment += 1;
allPokemon.push(new Pokemon("Anorith", increment, "rock/bug"));
increment += 1;
allPokemon.push(new Pokemon("Armaldo", increment, "rock/bug"));
increment += 1;
allPokemon.push(new Pokemon("Feebas", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Milotic", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Castform", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Kecleon", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Shuppet", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Banette", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Duskull", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Dusclops", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Tropius", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Chimecho", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Absol", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Wynaut", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Snorunt", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Glalie", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Spheal", increment, "ice/water"));
increment += 1;
allPokemon.push(new Pokemon("Sealeo", increment, "ice/water"));
increment += 1;
allPokemon.push(new Pokemon("Walrein", increment, "ice/water"));
increment += 1;
allPokemon.push(new Pokemon("Clamperl", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Huntail", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Gorebyss", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Relicanth", increment, "water/rock"));
increment += 1;
allPokemon.push(new Pokemon("Luvdisc", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Bagon", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Shelgon", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Salamence", increment, "dragon/flying"));
increment += 1;
allPokemon.push(new Pokemon("Beldum", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Metang", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Metagross", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Regirock", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Regice", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Registeel", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Latias", increment, "dragon/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Latios", increment, "dragon/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Kyogre", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Groudon", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Rayquaza", increment, "dragon/flying"));
increment += 1;
allPokemon.push(new Pokemon("Jirachi", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Deoxys", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Turtwig", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Grotle", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Torterra", increment, "grass/ground"));
increment += 1;
allPokemon.push(new Pokemon("Chimchar", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Monferno", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Infernape", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Piplup", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Prinplup", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Empoleon", increment, "water/steel"));
increment += 1;
allPokemon.push(new Pokemon("Starly", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Staravia", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Staraptor", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Bidoof", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Bibarel", increment, "normal/water"));
increment += 1;
allPokemon.push(new Pokemon("Kricketot", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Kricketune", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Shinx", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Luxio", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Luxray", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Budew", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Roserade", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Cranidos", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Rampardos", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Shieldon", increment, "rock/steel"));
increment += 1;
allPokemon.push(new Pokemon("Bastiodon", increment, "rock/steel"));
increment += 1;
allPokemon.push(new Pokemon("Burmy", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Wormadam", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Mothim", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Combee", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Vespiquen", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Pachirisu", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Buizel", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Floatzel", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Cherubi", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Cherrim", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Shellos", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Gastrodon", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Ambipom", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Drifloon", increment, "ghost/flying"));
increment += 1;
allPokemon.push(new Pokemon("Drifblim", increment, "ghost/flying"));
increment += 1;
allPokemon.push(new Pokemon("Buneary", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Lopunny", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Mismagius", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Honchkrow", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Glameow", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Purugly", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Chingling", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Stunky", increment, "poison/dark"));
increment += 1;
allPokemon.push(new Pokemon("Skuntank", increment, "poison/dark"));
increment += 1;
allPokemon.push(new Pokemon("Bronzor", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Bronzong", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Bonsly", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Mime Jr.", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Happiny", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Chatot", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Spiritomb", increment, "ghost/dark"));
increment += 1;
allPokemon.push(new Pokemon("Gible", increment, "dragon/ground"));
increment += 1;
allPokemon.push(new Pokemon("Gabite", increment, "dragon/ground"));
increment += 1;
allPokemon.push(new Pokemon("Garchomp", increment, "dragon/ground"));
increment += 1;
allPokemon.push(new Pokemon("Munchlax", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Riolu", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Lucario", increment, "fighting/steel"));
increment += 1;
allPokemon.push(new Pokemon("Hippopotas", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Hippowdon", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Skorupi", increment, "poison/bug"));
increment += 1;
allPokemon.push(new Pokemon("Drapion", increment, "poison/dark"));
increment += 1;
allPokemon.push(new Pokemon("Croagunk", increment, "poison/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Toxicroak", increment, "poison/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Carnivine", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Finneon", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Lumineon", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Mantyke", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Snover", increment, "grass/ice"));
increment += 1;
allPokemon.push(new Pokemon("Abomasnow", increment, "grass/ice"));
increment += 1;
allPokemon.push(new Pokemon("Weavile", increment, "dark/ice"));
increment += 1;
allPokemon.push(new Pokemon("Magnezone", increment, "electric/steel"));
increment += 1;
allPokemon.push(new Pokemon("Lickilicky", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Rhyperior", increment, "ground/rock"));
increment += 1;
allPokemon.push(new Pokemon("Tangrowth", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Electivire", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Magmortar", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Togekiss", increment, "fairy/flying"));
increment += 1;
allPokemon.push(new Pokemon("Yanmega", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Leafeon", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Glaceon", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Gliscor", increment, "ground/flying"));
increment += 1;
allPokemon.push(new Pokemon("Mamoswine", increment, "ice/ground"));
increment += 1;
allPokemon.push(new Pokemon("Porygon-Z", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Gallade", increment, "psychic/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Probopass", increment, "rock/steel"));
increment += 1;
allPokemon.push(new Pokemon("Dusknoir", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Froslass", increment, "ice/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Rotom", increment, "electric/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Uxie", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Mesprit", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Azelf", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Dialga", increment, "steel/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Palkia", increment, "water/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Heatran", increment, "fire/steel"));
increment += 1;
allPokemon.push(new Pokemon("Regigigas", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Giratina", increment, "ghost/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Cresselia", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Phione", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Manaphy", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Darkrai", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Shaymin", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Arceus", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Victini", increment, "psychic/fire"));
increment += 1;
allPokemon.push(new Pokemon("Snivy", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Servine", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Serperior", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Tepig", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Pignite", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Emboar", increment, "fire/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Oshawott", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Dewott", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Samurott", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Patrat", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Watchog", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Lillipup", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Herdier", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Stoutland", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Purrloin", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Liepard", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Pansage", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Simisage", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Pansear", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Simisear", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Panpour", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Simipour", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Munna", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Musharna", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Pidove", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Tranquill", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Unfezant", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Blitzle", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Zebstrika", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Roggenrola", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Boldore", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Gigalith", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Woobat", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Swoobat", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Drilbur", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Excadrill", increment, "ground/steel"));
increment += 1;
allPokemon.push(new Pokemon("Audino", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Timburr", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Gurdurr", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Conkeldurr", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Tympole", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Palpitoad", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Seismitoad", increment, "water/ground"));
increment += 1;
allPokemon.push(new Pokemon("Throh", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sawk", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sewaddle", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Swadloon", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Leavanny", increment, "bug/grass"));
increment += 1;
allPokemon.push(new Pokemon("Venipede", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Whirlipede", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Scolipede", increment, "bug/poison"));
increment += 1;
allPokemon.push(new Pokemon("Cottonee", increment, "grass/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Whimsicott", increment, "grass/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Petilil", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Lilligant", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Basculin", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Sandile", increment, "ground/dark"));
increment += 1;
allPokemon.push(new Pokemon("Krokorok", increment, "ground/dark"));
increment += 1;
allPokemon.push(new Pokemon("Krookodile", increment, "ground/dark"));
increment += 1;
allPokemon.push(new Pokemon("Darumaka", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Darmanitan", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Maractus", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Dwebble", increment, "bug/rock"));
increment += 1;
allPokemon.push(new Pokemon("Crustle", increment, "bug/rock"));
increment += 1;
allPokemon.push(new Pokemon("Scraggy", increment, "dark/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Scrafty", increment, "dark/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sigilyph", increment, "psychic/flying"));
increment += 1;
allPokemon.push(new Pokemon("Yamask", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Cofagrigus", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Tirtouga", increment, "water/rock"));
increment += 1;
allPokemon.push(new Pokemon("Carracosta", increment, "water/rock"));
increment += 1;
allPokemon.push(new Pokemon("Archen", increment, "rock/flying"));
increment += 1;
allPokemon.push(new Pokemon("Archeops", increment, "rock/flying"));
increment += 1;
allPokemon.push(new Pokemon("Trubbish", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Garbodor", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Zorua", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Zoroark", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Minccino", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Cinccino", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Gothita", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Gothorita", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Gothitelle", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Solosis", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Duosion", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Reuniclus", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Ducklett", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Swanna", increment, "water/flying"));
increment += 1;
allPokemon.push(new Pokemon("Vanillite", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Vanillish", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Vanilluxe", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Deerling", increment, "normal/grass"));
increment += 1;
allPokemon.push(new Pokemon("Sawsbuck", increment, "normal/grass"));
increment += 1;
allPokemon.push(new Pokemon("Emolga", increment, "electric/flying"));
increment += 1;
allPokemon.push(new Pokemon("Karrablast", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Escavalier", increment, "bug/steel"));
increment += 1;
allPokemon.push(new Pokemon("Foongus", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Amoonguss", increment, "grass/poison"));
increment += 1;
allPokemon.push(new Pokemon("Frillish", increment, "water/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Jellicent", increment, "water/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Alomomola", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Joltik", increment, "bug/electric"));
increment += 1;
allPokemon.push(new Pokemon("Galvantula", increment, "bug/electric"));
increment += 1;
allPokemon.push(new Pokemon("Ferroseed", increment, "grass/steel"));
increment += 1;
allPokemon.push(new Pokemon("Ferrothorn", increment, "grass/steel"));
increment += 1;
allPokemon.push(new Pokemon("Klink", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Klang", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Klinklang", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Tynamo", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Eelektrik", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Eelektross", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Elgyem", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Beheeyem", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Litwick", increment, "ghost/fire"));
increment += 1;
allPokemon.push(new Pokemon("Lampent", increment, "ghost/fire"));
increment += 1;
allPokemon.push(new Pokemon("Chandelure", increment, "ghost/fire"));
increment += 1;
allPokemon.push(new Pokemon("Axew", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Fraxure", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Haxorus", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Cubchoo", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Beartic", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Cryogonal", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Shelmet", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Accelgor", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Stunfisk", increment, "ground/electric"));
increment += 1;
allPokemon.push(new Pokemon("Mienfoo", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Mienshao", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Druddigon", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Golett", increment, "ground/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Golurk", increment, "ground/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Pawniard", increment, "dark/steel"));
increment += 1;
allPokemon.push(new Pokemon("Bisharp", increment, "dark/steel"));
increment += 1;
allPokemon.push(new Pokemon("Bouffalant", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Rufflet", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Braviary", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Vullaby", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Mandibuzz", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Heatmor", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Durant", increment, "bug/steel"));
increment += 1;
allPokemon.push(new Pokemon("Deino", increment, "dark/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Zweilous", increment, "dark/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Hydreigon", increment, "dark/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Larvesta", increment, "bug/fire"));
increment += 1;
allPokemon.push(new Pokemon("Volcarona", increment, "bug/fire"));
increment += 1;
allPokemon.push(new Pokemon("Cobalion", increment, "steel/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Terrakion", increment, "rock/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Virizion", increment, "grass/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Tornadus", increment, "flying"));
increment += 1;
allPokemon.push(new Pokemon("Thundurus", increment, "electric/flying"));
increment += 1;
allPokemon.push(new Pokemon("Reshiram", increment, "dragon/fire"));
increment += 1;
allPokemon.push(new Pokemon("Zekrom", increment, "dragon/electric"));
increment += 1;
allPokemon.push(new Pokemon("Landorus", increment, "ground/flying"));
increment += 1;
allPokemon.push(new Pokemon("Kyurem", increment, "dragon/ice"));
increment += 1;
allPokemon.push(new Pokemon("Keldeo", increment, "water/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Meloetta", increment, "normal/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Genesect", increment, "bug/steel"));
increment += 1;
allPokemon.push(new Pokemon("Chespin", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Quilladin", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Chesnaught", increment, "grass/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Fennekin", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Braixen", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Delphox", increment, "fire/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Froakie", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Frogadier", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Greninja", increment, "water/dark"));
increment += 1;
allPokemon.push(new Pokemon("Bunnelby", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Diggersby", increment, "normal/ground"));
increment += 1;
allPokemon.push(new Pokemon("Fletchling", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Fletchinder", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Talonflame", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Scatterbug", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Spewpa", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Vivillon", increment, "bug/flying"));
increment += 1;
allPokemon.push(new Pokemon("Litleo", increment, "fire/normal"));
increment += 1;
allPokemon.push(new Pokemon("Pyroar", increment, "fire/normal"));
increment += 1;
allPokemon.push(new Pokemon("Flabebe", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Floette", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Florges", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Skiddo", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Gogoat", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Pancham", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Pangoro", increment, "fighting/dark"));
increment += 1;
allPokemon.push(new Pokemon("Furfrou", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Espurr", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Meowstic", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Honedge", increment, "steel/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Doublade", increment, "steel/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Aegislash", increment, "steel/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Spritzee", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Aromatisse", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Swirlix", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Slurpuff", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Inkay", increment, "dark/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Malamar", increment, "dark/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Binacle", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Barbaracle", increment, "rock/water"));
increment += 1;
allPokemon.push(new Pokemon("Skrelp", increment, "poison/water"));
increment += 1;
allPokemon.push(new Pokemon("Dragalge", increment, "poison/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Clauncher", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Clawitzer", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Helioptile", increment, "electric/normal"));
increment += 1;
allPokemon.push(new Pokemon("Heliolisk", increment, "electric/normal"));
increment += 1;
allPokemon.push(new Pokemon("Tyrunt", increment, "rock/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Tyrantrum", increment, "rock/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Amaura", increment, "rock/ice"));
increment += 1;
allPokemon.push(new Pokemon("Aurorus", increment, "rock/ice"));
increment += 1;
allPokemon.push(new Pokemon("Sylveon", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Hawlucha", increment, "fighting/flying"));
increment += 1;
allPokemon.push(new Pokemon("Dedenne", increment, "electric/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Carbink", increment, "rock/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Goomy", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Sliggoo", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Goodra", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Klefki", increment, "steel/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Phantump", increment, "ghost/grass"));
increment += 1;
allPokemon.push(new Pokemon("Trevenant", increment, "ghost/grass"));
increment += 1;
allPokemon.push(new Pokemon("Pumpkaboo", increment, "ghost/grass"));
increment += 1;
allPokemon.push(new Pokemon("Gourgeist", increment, "ghost/grass"));
increment += 1;
allPokemon.push(new Pokemon("Bergmite", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Avalugg", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Noibat", increment, "flying/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Noivern", increment, "flying/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Xerneas", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Yveltal", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Zygarde", increment, "dragon/ground"));
increment += 1;
allPokemon.push(new Pokemon("Diancie", increment, "rock/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Hoopa", increment, "psychic/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Volcanion", increment, "fire/water"));
increment += 1;
allPokemon.push(new Pokemon("Rowlet", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Dartrix", increment, "grass/flying"));
increment += 1;
allPokemon.push(new Pokemon("Decidueye", increment, "grass/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Litten", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Torracat", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Incineroar", increment, "fire/dark"));
increment += 1;
allPokemon.push(new Pokemon("Popplio", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Brionne", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Primarina", increment, "water/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Pikipek", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Trumbeak", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Toucannon", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Yungoos", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Gumshoos", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Grubbin", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Charjabug", increment, "bug/electric"));
increment += 1;
allPokemon.push(new Pokemon("Vikavolt", increment, "bug/electric"));
increment += 1;
allPokemon.push(new Pokemon("Crabrawler", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Crabominable", increment, "fighting/ice"));
increment += 1;
allPokemon.push(new Pokemon("Oricorio", increment, "fire/flying"));
increment += 1;
allPokemon.push(new Pokemon("Cutiefly", increment, "bug/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Ribombee", increment, "bug/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Rockruff", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Lycanroc", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Wishiwashi", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Mareanie", increment, "poison/water"));
increment += 1;
allPokemon.push(new Pokemon("Toxapex", increment, "poison/water"));
increment += 1;
allPokemon.push(new Pokemon("Mudbray", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Mudsdale", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Dewpider", increment, "water/bug"));
increment += 1;
allPokemon.push(new Pokemon("Araquanid", increment, "water/bug"));
increment += 1;
allPokemon.push(new Pokemon("Fomantis", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Lurantis", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Morelull", increment, "grass/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Shiinotic", increment, "grass/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Salandit", increment, "poison/fire"));
increment += 1;
allPokemon.push(new Pokemon("Salazzle", increment, "poison/fire"));
increment += 1;
allPokemon.push(new Pokemon("Stufful", increment, "normal/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Bewear", increment, "normal/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Bounsweet", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Steenee", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Tsareena", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Comfey", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Oranguru", increment, "normal/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Passimian", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Wimpod", increment, "bug/water"));
increment += 1;
allPokemon.push(new Pokemon("Golisopod", increment, "bug/water"));
increment += 1;
allPokemon.push(new Pokemon("Sandygast", increment, "ghost/ground"));
increment += 1;
allPokemon.push(new Pokemon("Palossand", increment, "ghost/ground"));
increment += 1;
allPokemon.push(new Pokemon("Pyukumuku", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Type: Null", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Silvally", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Minior", increment, "rock/flying"));
increment += 1;
allPokemon.push(new Pokemon("Komala", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Turtonator", increment, "fire/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Togedemaru", increment, "electric/steel"));
increment += 1;
allPokemon.push(new Pokemon("Mimikyu", increment, "ghost/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Bruxish", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Drampa", increment, "normal/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Dhelmise", increment, "ghost/grass"));
increment += 1;
allPokemon.push(new Pokemon("Jangmo-o", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Hakamo-o", increment, "dragon/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Kommo-o", increment, "dragon/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Tapu Koko", increment, "electric/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Tapu Lele", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Tapu Bulu", increment, "grass/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Tapu Fini", increment, "water/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Cosmog", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Cosmoem", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Solgaleo", increment, "psychic/steel"));
increment += 1;
allPokemon.push(new Pokemon("Lunala", increment, "psychic/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Nihilego", increment, "rock/poison"));
increment += 1;
allPokemon.push(new Pokemon("Buzzwole", increment, "bug/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Pheromosa", increment, "bug/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Xurkitree", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Celesteela", increment, "steel/flying"));
increment += 1;
allPokemon.push(new Pokemon("Kartana", increment, "grass/steel"));
increment += 1;
allPokemon.push(new Pokemon("Guzzlord", increment, "dark/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Necrozma", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Magearna", increment, "steel/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Marshadow", increment, "fighting/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Poipole", increment, "poison"));
increment += 1;
allPokemon.push(new Pokemon("Naganadel", increment, "poison/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Stakataka", increment, "rock/steel"));
increment += 1;
allPokemon.push(new Pokemon("Blacephalon", increment, "fire/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Zeraora", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Meltan", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Melmetal", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Grookey", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Thwackey", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Rillaboom", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Scorbunny", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Raboot", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Cinderace", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Sobble", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Drizzile", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Inteleon", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Skwovet", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Greedent", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Rookidee", increment, "flying"));
increment += 1;
allPokemon.push(new Pokemon("Corvisquire", increment, "flying"));
increment += 1;
allPokemon.push(new Pokemon("Corviknight", increment, "flying/steel"));
increment += 1;
allPokemon.push(new Pokemon("Blipbug", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Dottler", increment, "bug/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Orbeetle", increment, "bug/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Nickit", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Thievul", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Gossifleur", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Eldegoss", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Wooloo", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Dubwool", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Chewtle", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Drednaw", increment, "water/rock"));
increment += 1;
allPokemon.push(new Pokemon("Yamper", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Boltund", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Rolycoly", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Carkol", increment, "rock/fire"));
increment += 1;
allPokemon.push(new Pokemon("Coalossal", increment, "rock/fire"));
increment += 1;
allPokemon.push(new Pokemon("Applin", increment, "grass/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Flapple", increment, "grass/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Appletun", increment, "grass/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Silicobra", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Sandaconda", increment, "ground"));
increment += 1;
allPokemon.push(new Pokemon("Cramorant", increment, "flying/water"));
increment += 1;
allPokemon.push(new Pokemon("Arrokuda", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Barraskewda", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Toxel", increment, "electric/poison"));
increment += 1;
allPokemon.push(new Pokemon("Toxtricity", increment, "electric/poison"));
increment += 1;
allPokemon.push(new Pokemon("Sizzlipede", increment, "fire/bug"));
increment += 1;
allPokemon.push(new Pokemon("Centiskorch", increment, "fire/bug"));
increment += 1;
allPokemon.push(new Pokemon("Clobbopus", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Grapploct", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sinistea", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Polteageist", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Hatenna", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Hattrem", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Hatterene", increment, "psychic/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Impidimp", increment, "dark/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Morgrem", increment, "dark/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Grimmsnarl", increment, "dark/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Obstagoon", increment, "dark/normal"));
increment += 1;
allPokemon.push(new Pokemon("Perrserker", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Cursola", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Sirfetch'd", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Mr. Rime", increment, "ice/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Runerigus", increment, "ground/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Milcery", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Alcremie", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Falinks", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Pincurchin", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Snom", increment, "ice/bug"));
increment += 1;
allPokemon.push(new Pokemon("Frosmoth", increment, "ice/bug"));
increment += 1;
allPokemon.push(new Pokemon("Stonjourner", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Eiscue", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Indeedee", increment, "psychic/normal"));
increment += 1;
allPokemon.push(new Pokemon("Morpeko", increment, "electric/dark"));
increment += 1;
allPokemon.push(new Pokemon("Cufant", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Copperajah", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Dracozolt", increment, "electric/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Arctozolt", increment, "electric/ice"));
increment += 1;
allPokemon.push(new Pokemon("Dracovish", increment, "water/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Arctovish", increment, "water/ice"));
increment += 1;
allPokemon.push(new Pokemon("Duraludon", increment, "steel/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Dreepy", increment, "dragon/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Drakloak", increment, "dragon/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Dragapult", increment, "dragon/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Zacian", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Zamazenta", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Eternatus", increment, "poison/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Kubfu", increment, "fighting"));
increment += 1;
allPokemon.push(new Pokemon("Urshifu", increment, "fighting/dark"));
increment += 1;
allPokemon.push(new Pokemon("Zarude", increment, "dark/grass"));
increment += 1;
allPokemon.push(new Pokemon("Regieleki", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Regidrago", increment, "dragon"));
increment += 1;
allPokemon.push(new Pokemon("Glastrier", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Spectrier", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Calyrex", increment, "psychic/grass"));
increment += 1;
allPokemon.push(new Pokemon("Wyrdeer", increment, "normal/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Kleavor", increment, "bug/rock"));
increment += 1;
allPokemon.push(new Pokemon("Ursaluna", increment, "ground/normal"));
increment += 1;
allPokemon.push(new Pokemon("Basculegion", increment, "water/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Sneasler", increment, "fighting/poison"));
increment += 1;
allPokemon.push(new Pokemon("Overqwil", increment, "dark/poison"));
increment += 1;
allPokemon.push(new Pokemon("Enamorus", increment, "fairy/flying"));
increment += 1;
allPokemon.push(new Pokemon("Sprigatito", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Floragato", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Meowscarada", increment, "grass/dark"));
increment += 1;
allPokemon.push(new Pokemon("Fuecoco", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Crocalor", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Skeledirge", increment, "fire/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Quaxly", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Quaxwell", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Quaquaval", increment, "water/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Lechonk", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Oinkologne", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Tarountula", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Spidops", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Nymble", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Lokix", increment, "bug/dark"));
increment += 1;
allPokemon.push(new Pokemon("Pawmi", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Pawmo", increment, "electric/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Pawmot", increment, "electric/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Tandemaus", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Maushold", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Fidough", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Dachsbun", increment, "fairy"));
increment += 1;
allPokemon.push(new Pokemon("Smoliv", increment, "grass/normal"));
increment += 1;
allPokemon.push(new Pokemon("Dolliv", increment, "grass/normal"));
increment += 1;
allPokemon.push(new Pokemon("Arboliva", increment, "grass/normal"));
increment += 1;
allPokemon.push(new Pokemon("Squawkabilly", increment, "normal/flying"));
increment += 1;
allPokemon.push(new Pokemon("Nacli", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Naclstack", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Garganacl", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Charcadet", increment, "fire"));
increment += 1;
allPokemon.push(new Pokemon("Armarouge", increment, "fire/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Ceruledge", increment, "fire/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Tadbulb", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Bellibolt", increment, "electric"));
increment += 1;
allPokemon.push(new Pokemon("Wattrel", increment, "electric/flying"));
increment += 1;
allPokemon.push(new Pokemon("Kilowattrel", increment, "electric/flying"));
increment += 1;
allPokemon.push(new Pokemon("Maschiff", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Mabosstiff", increment, "dark"));
increment += 1;
allPokemon.push(new Pokemon("Shroodle", increment, "poison/normal"));
increment += 1;
allPokemon.push(new Pokemon("Grafaiai", increment, "poison/normal"));
increment += 1;
allPokemon.push(new Pokemon("Bramblin", increment, "grass/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Brambleghast", increment, "grass/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Toedscool", increment, "ground/grass"));
increment += 1;
allPokemon.push(new Pokemon("Toedscruel", increment, "ground/grass"));
increment += 1;
allPokemon.push(new Pokemon("Klawf", increment, "rock"));
increment += 1;
allPokemon.push(new Pokemon("Capsakid", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Scovillain", increment, "grass/fire"));
increment += 1;
allPokemon.push(new Pokemon("Rellor", increment, "bug"));
increment += 1;
allPokemon.push(new Pokemon("Rabsca", increment, "bug/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Flittle", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Espathra", increment, "psychic"));
increment += 1;
allPokemon.push(new Pokemon("Tinkatink", increment, "fairy/steel"));
increment += 1;
allPokemon.push(new Pokemon("Tinkatuff", increment, "fairy/steel"));
increment += 1;
allPokemon.push(new Pokemon("Tinkaton", increment, "fairy/steel"));
increment += 1;
allPokemon.push(new Pokemon("Wiglett", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Wugtrio", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Bombirdier", increment, "flying/dark"));
increment += 1;
allPokemon.push(new Pokemon("Finizen", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Palafin", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Varoom", increment, "steel/poison"));
increment += 1;
allPokemon.push(new Pokemon("Revavroom", increment, "steel/poison"));
increment += 1;
allPokemon.push(new Pokemon("Cyclizar", increment, "dragon/normal"));
increment += 1;
allPokemon.push(new Pokemon("Orthworm", increment, "steel"));
increment += 1;
allPokemon.push(new Pokemon("Glimmet", increment, "rock/poison"));
increment += 1;
allPokemon.push(new Pokemon("Glimmora", increment, "rock/poison"));
increment += 1;
allPokemon.push(new Pokemon("Greavard", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Houndstone", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Flamigo", increment, "flying/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Cetoddle", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Cetitan", increment, "ice"));
increment += 1;
allPokemon.push(new Pokemon("Veluza", increment, "water/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Dondozo", increment, "water"));
increment += 1;
allPokemon.push(new Pokemon("Tatsugiri", increment, "dragon/water"));
increment += 1;
allPokemon.push(new Pokemon("Annihilape", increment, "fighting/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Clodsire", increment, "poison/ground"));
increment += 1;
allPokemon.push(new Pokemon("Farigiraf", increment, "normal/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Dudunsparce", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Kingambit", increment, "dark/steel"));
increment += 1;
allPokemon.push(new Pokemon("Great Tusk", increment, "ground/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Scream Tail", increment, "fairy/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Brute Bonnet", increment, "grass/dark"));
increment += 1;
allPokemon.push(new Pokemon("Flutter Mane", increment, "ghost/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Slither Wing", increment, "bug/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Sandy Shocks", increment, "electric/ground"));
increment += 1;
allPokemon.push(new Pokemon("Iron Treads", increment, "ground/steel"));
increment += 1;
allPokemon.push(new Pokemon("Iron Bundle", increment, "ice/water"));
increment += 1;
allPokemon.push(new Pokemon("Iron Hands", increment, "fighting/electric"));
increment += 1;
allPokemon.push(new Pokemon("Iron Jugulis", increment, "dark/flying"));
increment += 1;
allPokemon.push(new Pokemon("Iron Moth", increment, "fire/poison"));
increment += 1;
allPokemon.push(new Pokemon("Iron Thorns", increment, "rock/electric"));
increment += 1;
allPokemon.push(new Pokemon("Frigibax", increment, "dragon/ice"));
increment += 1;
allPokemon.push(new Pokemon("Arctibax", increment, "dragon/ice"));
increment += 1;
allPokemon.push(new Pokemon("Baxcalibur", increment, "dragon/ice"));
increment += 1;
allPokemon.push(new Pokemon("Gimmighoul", increment, "ghost"));
increment += 1;
allPokemon.push(new Pokemon("Gholdengo", increment, "steel/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Wo-Chien", increment, "dark/grass"));
increment += 1;
allPokemon.push(new Pokemon("Chien-Pao", increment, "dark/ice"));
increment += 1;
allPokemon.push(new Pokemon("Ting-Lu", increment, "dark/ground"));
increment += 1;
allPokemon.push(new Pokemon("Chi-Yu", increment, "dark/fire"));
increment += 1;
allPokemon.push(new Pokemon("Roaring Moon", increment, "dragon/dark"));
increment += 1;
allPokemon.push(new Pokemon("Iron Valiant", increment, "fairy/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Koraidon", increment, "fighting/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Miraidon", increment, "electric/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Walking Wake", increment, "water/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Iron Leaves", increment, "grass/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Dipplin", increment, "grass/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Poltchageist", increment, "grass/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Sinistcha", increment, "grass/ghost"));
increment += 1;
allPokemon.push(new Pokemon("Okidogi", increment, "poison/fighting"));
increment += 1;
allPokemon.push(new Pokemon("Munkidori", increment, "poison/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Fezandipiti", increment, "poison/fairy"));
increment += 1;
allPokemon.push(new Pokemon("Ogerpon", increment, "grass"));
increment += 1;
allPokemon.push(new Pokemon("Archaludon", increment, "steel/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Hydrapple", increment, "grass/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Gouging Fire", increment, "fire/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Raging Bolt", increment, "electric/dragon"));
increment += 1;
allPokemon.push(new Pokemon("Iron Boulder", increment, "rock/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Iron Crown", increment, "steel/psychic"));
increment += 1;
allPokemon.push(new Pokemon("Terapagos", increment, "normal"));
increment += 1;
allPokemon.push(new Pokemon("Pecharunt", increment, "poison/ghost"));
increment += 1;

window.allPokemon = allPokemon